from pygame.locals import *

# level/display constants
NUM_LEVEL_TILES_X = 35
NUM_LEVEL_TILES_Y = 19

TILE_WIDTH = 32
TILE_HEIGHT = 32

BOTTOM_BAR_HEIGHT = 0
BOTTOM_BAR_WIDTH = NUM_LEVEL_TILES_X * TILE_WIDTH

SCREEN_WIDTH = NUM_LEVEL_TILES_X * TILE_WIDTH
SCREEN_HEIGHT = NUM_LEVEL_TILES_Y * TILE_HEIGHT + BOTTOM_BAR_HEIGHT

GAME_SCREEN_WIDTH = NUM_LEVEL_TILES_X * TILE_WIDTH
GAME_SCREEN_HEIGHT = NUM_LEVEL_TILES_Y * TILE_HEIGHT

FRAME_RATE = 60

# player/agent constants

RIGHT_KEY = K_d
LEFT_KEY = K_a
JUMP_KEY = K_w

PLAYER_XV_INCREMENT = 0.5
AGENT_XV_INCREMENT = 0.3

GRAVITY_INCREMENT = 0.3

JUMP_INCREMENT = 6
AGENT_JUMP_INCREMENT = 6

FRICTION = 0.1

MAXIMUM_VELOCITY = 32

PLAYER_BOUNCE_FACTOR = 0.2

AGENT_LOS = 100
AGENT_FAILURE_COUNTDOWN = 200

# Debugging/Utility Constants
TRACE_ON = False
BOUNDING_BOX_ON = False
AI_INDICATORS_ON = False