from pygame.locals import *

# level/display constants
NUM_LEVEL_TILES_X = 35
NUM_LEVEL_TILES_Y = 19

TILE_WIDTH = 32
TILE_HEIGHT = 32




GAME_SCREEN_WIDTH = NUM_LEVEL_TILES_X * TILE_WIDTH
GAME_SCREEN_HEIGHT = NUM_LEVEL_TILES_Y * TILE_HEIGHT

BOTTOM_BAR_HEIGHT = 32
BOTTOM_BAR_WIDTH = NUM_LEVEL_TILES_X * TILE_WIDTH
BOTTOM_BAR_START = GAME_SCREEN_HEIGHT

SCREEN_WIDTH = NUM_LEVEL_TILES_X * TILE_WIDTH
SCREEN_HEIGHT = NUM_LEVEL_TILES_Y * TILE_HEIGHT + BOTTOM_BAR_HEIGHT

FRAME_RATE = 60

# player/agent constants

RIGHT_KEY = K_d
LEFT_KEY = K_a
JUMP_KEY = K_w
DOWN_KEY = K_s

PLAYER_XV_INCREMENT = 0.4
AGENT_XV_INCREMENT = 0.18

GRAVITY_INCREMENT = 0.3

JUMP_INCREMENT = 8
AGENT_JUMP_INCREMENT = 6

FRICTION = 0.05

COLLISION_BLOCK = 20

MAXIMUM_VELOCITY = 32

PUFF_THRESHOLD = 2

PLAYER_BOUNCE_FACTOR = 0.2

RAGE_DECREMENT = 0.03
RAGE_INCREMENT = 10

AGENT_LOS = 250
AGENT_FAILURE_COUNTDOWN = 200

# Graphical options
TRACE_ON = True
BOUNDING_BOX_ON = False
AI_INDICATORS_ON = False